services:
  postgres:
    container_name: postgres_sql_bs-network
    image: 'postgres'
    environment:
      POSTGRES_USER: username
      POSTGRES_DB: book_service_networkDB
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - spring-demo

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:26.2.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-demo
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
